### ISSUE TITLE
Attaching Shadow hand to KUKA Arm

### ISSUE THREAD

**Issue by sivammt** [guihomework/dexterous-manipulation-tutorial#2]
I have issues in combining the urdf.xacro files of KUKA Arm and Shadow Hand. I tried attaching the files of KUKA Arm with barret hand and it worked well in simulation. But i cannot find the files for shadow hand of similar type. The barret hand urdf content is below. help me in finding such content for Shadow hand. Thank you

**Comment by sivammt** [comment]
sorry for the above file. I am attaching the jpg file below
![output-page-003](https://cloud.githubusercontent.com/assets/10954679/6526052/ab205004-c40d-11e4-818f-61448c64c8a4.jpg)
![output-page-004](https://cloud.githubusercontent.com/assets/10954679/6526053/ab23ca4a-c40d-11e4-8249-39df46f8f49e.jpg)
![output-page-005](https://cloud.githubusercontent.com/assets/10954679/6526056/ab259ece-c40d-11e4-8554-ea6b9a855253.jpg)
![output-page-006](https://cloud.githubusercontent.com/assets/10954679/6526055/ab259780-c40d-11e4-8f08-2ac5abb0f1d8.jpg)
![output-page-007](https://cloud.githubusercontent.com/assets/10954679/6526054/ab255c66-c40d-11e4-894d-f69667fdfa8b.jpg)

**Comment by guihomework** [comment]
On the shadow hand everything is generated via macros. Please look at sr_description/robots/arm_and_hand_motor.urdf.xacro 
it is basically a description doing
world -> world to arm joint -> arm macro -> arm to hand joint ->hand macro

the way to go for you is then 
world -> world to kuka joint -> kuka -> kuka to shadow fixed joint -> hand macro.

of course this creates a xacro file that should be expanded with a xacro.py call (this is standard to load robot_description on the fly)

In the future, I suggest to ask these questions to the shadow robot team over their github,  I also answer there as I participate to their developments, and this is more related to shadow than this tutorial is meant for.

**Comment by sivammt** [comment]
Thanks a lot for the solution. In case i get any further queries i will ask  in shadow robot git-hub page.
