### ISSUE TITLE
compatibility issues with moveit! and gazebo

### ISSUE THREAD

**Issue by sivammt** [guihomework/dexterous-manipulation-tutorial#3]
I am working with Shadow Hand with BioTac. I have used moveit! to simulate the model. When I compile movegroup interface codes, I can visualize the change in joint movements (as per the codes) in the rviz window. till this point everything is perfect. Now I want to give this code to the real hand. before that I would like to test this with gazebo simulator. when I try to pass commands to the hand in gazebo, my process dies.

[moveit_shadow-6] process has died [pid 12737, exit code -11, cmd /home/siva/catkin_ws/devel/lib/pr2_moveit_tutorials/moveit_shadow __name:=moveit_shadow __log:=/home/siva/.ros/log/559965ae-e4dc-11e4-ab94-038151540a1b/moveit_shadow-6.log].
log file: /home/siva/.ros/log/559965ae-e4dc-11e4-ab94-038151540a1b/moveit_shadow-6*.log

kindly give me  solution to pass codes from moveit! to simulate in gazebo.

**Comment by guihomework** [comment]
This is indeed a missing point of this tutorial. Shadow has been working on adding a trajectory execution controller for the hand joints while I created the tutorial, but I did not look if this is ready now. I have no solution out of the box right now but will look at it within a few days. 

I found an email from the Shadow software team saying they tested the generic joint_trajectory_controller connected to their ros_control position controllers. 
```
robot_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - FFJ1
    - FFJ2
     .......
```
Maybe you can ask them on this topic https://github.com/shadow-robot/sr-ros-interface/issues/172 
 if they already solved that.
When I will test this, it will be in this direction as well. Stay tuned.

**Comment by guihomework** [comment]
I have been very busy and as I had seen Shadow working on this subject just after you asked the question, I thought I would wait for them to put up a solution. 

You asked them (https://github.com/shadow-robot/sr-ros-interface/issues/264) and they pointed you to their newer code not exactly using the same result of the tutorial (they redid a UR+shadow moveit config for some unknown reasons).  What is especially important I would say is 
https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_robot_launch/config/rh_trajectory_controller.yaml
which defines the trajectory controller you were missing for the hand. This newer controller uses ros_control to send joint values to position_joint_controllers (they do a kind of nesting of controllers). I think this is only available in indigo.
If you have such trajectory controller running, then moveit must find them
following the example here https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_multi_moveit/ur10srh_moveit_config/launch/ur10srh_moveit_controller_manager.launch.xml
edit your  shadowhand_motor_moveit_controller_manager.launch.xml in a similar fashion and create a controllers.yaml similar to https://github.com/shadow-robot/sr-ros-interface/blob/indigo-devel/sr_multi_moveit/ur10srh_moveit_config/config/controllers.yaml

I think if you stay with hydro there is no great options. I can release some code I did in the past that executes some trajectory as an actionlib (not in the control loop) but that requires some update to run in indigo.
