### ISSUE TITLE
issue launching

### ISSUE THREAD

**Issue by guihomework** [guihomework/dexterous-manipulation-tutorial#4]
reported by  iro2014002   

> Hello, I'm was trying out the simulation of shadow_ur10arm

```
Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main
    eval_self_contained(doc)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained
    eval_all(doc.documentElement, macros, symbols)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 552, in eval_all
    (",".join(params), str(node.tagName)))
xacro.XacroException: Parameters [lf] were not set for macro xacro:shadowhand
while processing /home/lhilo/My_WorkSpace/shadow_robot/src/dexterous-manipulation-tutorial-master/sr_multi_moveit/shadow_ur10_moveit_config/launch/planning_context.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/lhilo/My_WorkSpace/shadow_robot/src/sr_interface-indigo-devel/sr_multi_description/urdf/shadow_ur10_joint_limited.urdf.xacro'] returned with code [1].


Param xml is <param command="$(find xacro)/xacro.py '$(find sr_multi_description)/urdf/shadow_ur10_joint_limited.urdf.xacro'" if="$(arg limited)" name="$(arg robot_description)"/>
The traceback for the exception was written to the log file
```

**Comment by ugocupcic** [comment]
Just a quick  comment from my side, make sure you're using these instructions to install Shadow Robot's code: 
http://shadow-robot.readthedocs.org/en/latest/generated/shadow_robot/INSTALL.html

**Comment by guihomework** [comment]
@ugocupcic I was going to use released shadow code in indigo as I did for this tutorial, and just overlay what I need to be different (kind of fetching newest feature and keeping then in this repository). Maybe some of these features made into indigo (releases, not devel branches) now and I can use them. This might be even simpler.

I will see

**Comment by ugocupcic** [comment]
OK whatever is the simplest for you!

On 27 April 2016 at 11:16, GuiHome <notifications@github.com> wrote:

> @ugocupcic <https://github.com/ugocupcic> I was going to use released
> shadow code in indigo as I did for this tutorial, and just overlay what I
> need to be different (kind of fetching newest feature and keeping then in
> this repository). Maybe some of these features made into indigo (releases,
> not devel branches) now and I can use them. This might be even simpler.
>
> I will see
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/guihomework/dexterous-manipulation-tutorial/issues/4#issuecomment-215023096>
>



-- 
Ugo Cupcic*Chief Technical Architect*+44 20 7700 2487

-- 

------------------------------
*Shadow Robot Company Ltd.*
251 Liverpool Road, N1 1LX, UK
Registered Number 3308007 (England & Wales)
------------------------------

**Comment by guihomework** [comment]
the released indigo sr_description does not need the lf parameter in the macro but the recent indigo-devel code requires it indeed https://github.com/shadow-robot/sr_common/blob/indigo-devel/sr_description/hand/xacro/full_hand.urdf.xacro#L21

Since the second part of this tutorial gives a .rosinstall to compile from source the minimal number of shadow packages required, the .rosinstall is the culprit. 
It should point to specific revisions of the shadow repository instead of indigo-devel which seems to not be backward compatible (actually newer xacro also backported in indigo could cope with default arguments for lf but not older xacro which shadow still uses). 
I will update the .rosinstall to also match the new repository structure of shadow (will be much simpler now as sr_description is separate)

**Comment by guihomework** [comment]
I updated the [rosinstall](https://raw.githubusercontent.com/wiki/guihomework/dexterous-manipulation-tutorial/media/.rosinstall) to point to specific git commits that work with this tutorial. 

Recent code added a lf parameter which is necessary 
just add lf="true"
in this line https://github.com/guihomework/dexterous-manipulation-tutorial/blob/master/sr_multi_description/urdf/shadow_ur10_joint_limited.urdf.xacro#L21
and this line
https://github.com/guihomework/dexterous-manipulation-tutorial/blob/master/sr_multi_description/urdf/shadow_ur10.urdf.xacro#L21

If you really want to run the latest shadow code and something else fails, open an new issue asking for updating the tutorial to the latest shadow code. I will see if I can find time to do that
